-- MySQL Script generated by MySQL Workbench
-- Thu Mar 15 00:50:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema comp1640
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema comp1640
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `comp1640` DEFAULT CHARACTER SET utf8 ;
USE `comp1640` ;

-- -----------------------------------------------------
-- Table `comp1640`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comp1640`.`accounts` (
  `acc_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `acc_type` TINYINT(1) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`acc_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Insert Sample Data Table `comp1640`.`accounts`
-- -----------------------------------------------------
INSERT INTO `comp1640`.`accounts` VALUES (1, "qa_manager", "123456", 2, "huybq.1992@gmail.com");
INSERT INTO `comp1640`.`accounts` VALUES (2, "qa_coordinator", "123456", 1, "huybq.1992@gmail.com");
INSERT INTO `comp1640`.`accounts` VALUES (3, "user1", "123456", 0, "huybq.1992@gmail.com");
INSERT INTO `comp1640`.`accounts` VALUES (5, "user2", "123456", 0, "huybq.1992@gmail.com");
INSERT INTO `comp1640`.`accounts` VALUES (4, "staff1", "123456", 3, "huybq.1992@gmail.com");
INSERT INTO `comp1640`.`accounts` VALUES (NULL, "staff2", "123456", 3, "huybq.1992@gmail.com");


-- -----------------------------------------------------
-- Table `comp1640`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comp1640`.`categories` (
  `cate_id` INT NOT NULL AUTO_INCREMENT,
  `cate_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cate_id`),
  UNIQUE INDEX `cate_name_UNIQUE` (`cate_name` ASC))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Insert Sample Data Table `comp1640`.`categories`
-- -----------------------------------------------------
INSERT INTO `comp1640`.`categories` VALUES (NULL, "General");
INSERT INTO `comp1640`.`categories` VALUES (NULL, "Information Technology");
INSERT INTO `comp1640`.`categories` VALUES (NULL, "Accounting & Finance");
INSERT INTO `comp1640`.`categories` VALUES (NULL, "Hospitality & Tourism");
INSERT INTO `comp1640`.`categories` VALUES (NULL, "Psychology");
INSERT INTO `comp1640`.`categories` VALUES (NULL, "Business");

-- -----------------------------------------------------
-- Table `comp1640`.`settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comp1640`.`settings` (
  `set_id` INT NOT NULL AUTO_INCREMENT,
  `set_name` VARCHAR(100) NOT NULL,
  `set_value` TIMESTAMP NOT NULL,
  PRIMARY KEY (`set_id`),
  UNIQUE INDEX `set_name_UNIQUE` (`set_name` ASC))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Insert Sample Data Table `comp1640`.`settings`
-- -----------------------------------------------------
INSERT INTO `comp1640`.`settings` VALUES (1, "Closure Date", '2018-05-01 00:00:00');
INSERT INTO `comp1640`.`settings` VALUES (2, "Final Closure Date", '2018-05-02 00:00:00');


-- -----------------------------------------------------
-- Table `comp1640`.`ideas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comp1640`.`ideas` (
  `idea_id` INT NOT NULL AUTO_INCREMENT,
  `idea_title` VARCHAR(200) NOT NULL,
  `idea_content` TEXT NULL,
  `idea_time` TIMESTAMP NOT NULL,
  `idea_anony` TINYINT(1) ZEROFILL NOT NULL,
  `accounts_acc_id` INT NOT NULL,
  `categories_cate_id` INT NOT NULL,
  `idea_filename` TEXT NULL,
  PRIMARY KEY (`idea_id`, `accounts_acc_id`, `categories_cate_id`),
  INDEX `fk_ideas_accounts_idx` (`accounts_acc_id` ASC),
  INDEX `fk_ideas_categories1_idx` (`categories_cate_id` ASC),
  CONSTRAINT `fk_ideas_accounts`
    FOREIGN KEY (`accounts_acc_id`)
    REFERENCES `comp1640`.`accounts` (`acc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ideas_categories1`
    FOREIGN KEY (`categories_cate_id`)
    REFERENCES `comp1640`.`categories` (`cate_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Sample data for Table `comp1640`.`ideas`
-- ----------------------------------------------------- 
INSERT INTO `ideas` (`idea_id`, `idea_title`, `idea_content`, `idea_time`, `idea_anony`, `accounts_acc_id`, `categories_cate_id`, `idea_filename`) VALUES
(NULL, 'Idea 1 from user1', 'No content', '2018-03-21 22:55:05', 1, 3, 4, NULL),
(NULL, 'Idea 1 from user2', 'No content', '2018-03-22 20:08:47', 1, 5, 1, NULL),
(NULL, 'Idea 2 from user1', 'No content', '2018-03-23 20:11:34', 0, 3, 1, NULL),
(NULL, 'Idea 2 from user2', 'No content', '2018-03-24 20:14:48', 0, 5, 2, NULL),
(NULL, 'Idea 3 from user2', 'No content', '2018-03-25 20:15:57', 1, 5, 3, NULL),
(NULL, 'Idea 4 from user2', 'No content', '2018-03-25 21:07:13', 0, 5, 4, NULL),
(NULL, 'Idea 3 from user1', 'No content', '2018-03-26 21:09:05', 0, 3, 2, NULL),
(NULL, 'Idea 4 from user1', 'No content', '2018-03-26 21:10:28', 0, 3, 3, NULL);


-- -----------------------------------------------------
-- Table `comp1640`.`thumbs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comp1640`.`thumbs` (
  `thumb_id` INT NOT NULL AUTO_INCREMENT,
  `thumb_type` TINYINT(1) ZEROFILL NOT NULL,
  `accounts_acc_id` INT NOT NULL,
  `ideas_idea_id` INT NOT NULL,
  `ideas_accounts_acc_id` INT NOT NULL,
  `ideas_categories_cate_id` INT NOT NULL,
  PRIMARY KEY (`thumb_id`, `accounts_acc_id`, `ideas_idea_id`, `ideas_accounts_acc_id`, `ideas_categories_cate_id`),
  INDEX `fk_thumbs_accounts1_idx` (`accounts_acc_id` ASC),
  INDEX `fk_thumbs_ideas1_idx` (`ideas_idea_id` ASC, `ideas_accounts_acc_id` ASC, `ideas_categories_cate_id` ASC),
  CONSTRAINT `fk_thumbs_accounts1`
    FOREIGN KEY (`accounts_acc_id`)
    REFERENCES `comp1640`.`accounts` (`acc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_thumbs_ideas1`
    FOREIGN KEY (`ideas_idea_id` , `ideas_accounts_acc_id` , `ideas_categories_cate_id`)
    REFERENCES `comp1640`.`ideas` (`idea_id` , `accounts_acc_id` , `categories_cate_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comp1640`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comp1640`.`comments` (
  `cm_id` INT NOT NULL AUTO_INCREMENT,
  `cm_content` TEXT NOT NULL,
  `ideas_idea_id` INT NOT NULL,
  `ideas_accounts_acc_id` INT NOT NULL,
  `ideas_categories_cate_id` INT NOT NULL,
  `cm_time` TIMESTAMP NOT NULL,
  `accounts_acc_id` INT NOT NULL,
  PRIMARY KEY (`cm_id`, `ideas_idea_id`, `ideas_accounts_acc_id`, `ideas_categories_cate_id`),
  INDEX `fk_comments_ideas1_idx` (`ideas_idea_id` ASC, `ideas_accounts_acc_id` ASC, `ideas_categories_cate_id` ASC),
  CONSTRAINT `fk_comments_ideas1`
    FOREIGN KEY (`ideas_idea_id` , `ideas_accounts_acc_id` , `ideas_categories_cate_id`)
    REFERENCES `comp1640`.`ideas` (`idea_id` , `accounts_acc_id` , `categories_cate_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
